services:

  app:
    build:
      context: .
      dockerfile: ./ops/docker/fpm/Dockerfile
      target: develop
    container_name: ${COMPOSE_PROJECT_NAME}-app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: develop
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
    #command: composer install
    networks:
      - app-local-network

  nginx:
    build:
      context: .
      dockerfile: ./ops/docker/nginx/Dockerfile
      target: develop
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: develop
    tty: true
    depends_on:
      - app
    ports:
      - "${COMPOSE_WEBSERVER_PORT}:80"
    networks:
      - app-local-network

  database:
    image: mariadb:10.3
    container_name: ${COMPOSE_PROJECT_NAME}-database
    tty: true
    ports:
      - "${COMPOSE_DB_PORT}:3306"
    environment:
      MYSQL_USER: appuser
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: develop
      SERVICE_NAME: database
    volumes:
      - ./data-database:/var/lib/mysql:delegated
    networks:
      - app-local-network

networks:
  app-local-network:
    driver: bridge
volumes:
  data-database:
    driver: local